### ISSUE TITLE
Ajuste do gráfico de monitoramento no Firefox

### ISSUE THREAD

**Issue by CelioBarros** [analytics-ufcg/sab#21]
Ajustar o gráfico de monitoramento on Firefox para não ultrapassar o eixo X.

**Comment by diegocoelho** [comment]
No chrome os pontos também estão extrapolando o limite

**Comment by jeffersonrpn** [comment]
Resolvido para o Chrome no commit de9d796 . Acho que o Firefox não implementa a propriedade CSS clip-path então não tem solução conhecida.
