### ISSUE TITLE
Escalar o tamanho dos reservatórios com log ao invés de 5 categorias

### ISSUE THREAD

**Issue by jeffersonrpn** [analytics-ufcg/sab#6]

**Comment by CelioBarros** [comment]
O Log não é tão bom no nosso caso porque o reservatório pequeno fica MUITO pequeno e o grande MUITO grande.

**Comment by nazareno** [comment]
O log resolve exatamente isso, Célio. Ele diminui essa diferença.
Tem que ser uma combinação de log com setar o mínimo no contradomínio (o
menor tamanho de ponto no gráfico).

**Comment by CelioBarros** [comment]
A gente testou isso também. Ficou um pouco melhor, agora pelo tamanho do mapa o log tem que ser utilizado log/2.
